apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositeclusters.hopin.com
  labels:
    provider: terraform
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: hopin.com/v1alpha1
    kind: CompositeCluster
  resources:
    - name: terraform-modules-eks
      base:
        apiVersion: tf.crossplane.io/v1alpha1
        kind: Workspace
        spec:
          forProvider:
            source: Remote
            module: github.com/hopin-team/terraform-modules/releases/tag/eks-cluster-v1.2.0
            vars:
              - key: environment
              - key: aws_region
              - key: name
              - key: profile
              - key: private_subnets
              - key: public_subnets
              - key: branch
              - key: flux_version
              - key: kubernetes_version
              - key: min_size
              - key: max_size
              - key: initial_size
              - key: instance_types
              - key: instance_disk_size
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.environemnt"
          toFieldPath: "spec.forProvider.vars[0].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.vars[1].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.vars[2].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.profile"
          toFieldPath: "spec.forProvider.vars[3].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.privateSubnets"
          toFieldPath: "spec.forProvider.vars[4].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.publicSubnets"
          toFieldPath: "spec.forProvider.vars[5].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.branch"
          toFieldPath: "spec.forProvider.vars[6].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.fluxVersion"
          toFieldPath: "spec.forProvider.vars[7].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.kubernetesVersion"
          toFieldPath: "spec.forProvider.vars[8].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.minSize"
          toFieldPath: "spec.forProvider.vars[9].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.maxSize"
          toFieldPath: "spec.forProvider.vars[10].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.initialSize"
          toFieldPath: "spec.forProvider.vars[11].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.instanceTypes"
          toFieldPath: "spec.forProvider.vars[12].value"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.instanceDiskSize"
          toFieldPath: "spec.forProvider.vars[13].value"
        # - type: FromCompositeFieldPath
        #   fromFieldPath: "spec.parameters.location"
        #   toFieldPath: "spec.forProvider.vars[1].value"
        #   transforms:
        #     - type: map
        #       map:
        #         east-coast: us-east1-b
        #         west-coast: us-west1-b
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-cluster"
      connectionDetails:
        - fromConnectionSecretKey: endpoint
