apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: terraform-modules-eks
  annotations:
    provider: terraform
spec:
  crossplane:
    version: ">=v1.2.0"
  dependsOn:
    - provider: crossplane/provider-terraform
      version: "v0.1.2"
