---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeclusters.hopin.com
spec:
  group: hopin.com
  names:
    kind: CompositeCluster
    plural: compositeclusters
  claimNames:
    kind: Cluster
    plural: clusters
  connectionSecretKeys:
    - address
  defaultCompositionRef:
    name: compositeclusters.hopin.com
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    environment:
                      type: string
                      default: dev
                      enum:
                        - dev
                        - int
                        - evil
                        - prod
                        - scale
                        - stg
                    name:
                      type: string
                    region:
                      type: string
                      default: eu-west-1
                    profile:
                      type: string
                      default: default
                    privateSubnets:
                      type: array
                      items:
                        type: string
                    publicSubnets:
                      type: array
                      items:
                        type: string
                    branch:
                      type: string
                      default: main
                    fluxVersion:
                      type: string
                      default: "v0.22.0"
                    kubernetesVersion:
                      type: string
                      default: "1.19"
                    minSize:
                      type: integer
                      default: 3
                    maxSize:
                      type: integer
                      default: 10
                    initialSize:
                      type: integer
                      default: 3
                    instanceTypes:
                      type: array
                      items:
                        type: string
                      default:
                        - "c5.xlarge"
                    instanceDiskSize:
                      type: integer
                      default: 512
                  required:
                    - name
                    - privateSubnets
                    - publicSubnets
              required:
                - parameters
