apiVersion: hopin.com/v1alpha1
kind: Cluster
metadata:
  name: test-cluster
  annotations:
    crossplane.io/external-name: test-cluster
spec:
  parameters:
    environment: dev
    name: test-cluster
    privateSubnets:
      - subnet-00d3b7b6756188498
      - subnet-0bed84f36a7c6c30d
    publicSubnets:
      - subnet-0c0869aa18a47a45d
      - subnet-0decc2974c04199bf
  writeConnectionSecretToRef:
    name: test-cluster
